name: CI
#on: [push, pull_request]
on:
  push:
    branches:
      - bstack
  pull_request:
    # Sequence of patterns matched against refs/heads
    branches:    
      - bstack
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
        - name: Checkout
          uses: actions/checkout@v3
        - uses: actions/setup-node@v3
          with:
            node-version: 18
        - name: Install
          run: npm install
        - name: Test
          env:
            BROWSERSTACK_USERNAME: ${{secrcets.BROWSERSTACK_USERNAME}}
            BROWSERSTACK_ACCESS_KEY: ${{secrcets.BROWSERSTACK_ACCESS_KEY}}
          run: npm run wdio:bstack 
          continue-on-error: true
        - uses: actions/upload-artifact@v3
          with:
            name: allureReport
            path: ./reports/allure/allure-report